- id: Family Room Nightlight On
  alias: Family Room Nightlight On
  trigger:
  - event: sunset
    platform: sun
  action:
  - data:
      brightness_pct: 66
      entity_id: light.hue_family_room_nightlight
    service: light.turn_on
  initial_state: true
- id: Family Room Nightlight Off
  alias: Family Room Nightlight Off
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - entity_id: light.hue_family_room_nightlight
    service: light.turn_off
  initial_state: true
- id: Outside Lights On
  alias: Outside Lights On
  trigger:
  - event: sunset
    offset: +00:10:00
    platform: sun
  condition: []
  action:
  - data:
      brightness_pct: 60
      color_name: green
      entity_id: light.hue_garage_door_left
    service: light.turn_on
  - data:
      brightness_pct: 60
      color_name: red
      entity_id: light.hue_garage_door_right
    service: light.turn_on
  - data:
      brightness_pct: 10
      color_name: blue
      entity_id: light.hue_front_porch
    service: light.turn_on
  initial_state: true
- id: Outside Lights Off
  initial_state: true
  alias: Outside Lights Off
  trigger:
  - event: sunrise
    offset: -00:30:00
    platform: sun
  condition: []
  action:
  - data:
      entity_id: light.hue_garage_door_left
    service: light.turn_off
  - data:
      entity_id: light.hue_garage_door_right
    service: light.turn_off
  - data:
      entity_id: light.hue_front_porch
    service: light.turn_off
- id: Rachio zone 1
  alias: Rachio zone 1
  trigger:
  - at: '15:00:00'
    platform: time
  condition:
  - above: '80'
    condition: numeric_state
    entity_id: sensor.dark_sky_apparent_temperature
  action:
  - data:
      message: rachio zone 1 triggered
    service: notify.kyles_phone
