- id: '1541109387657'
  alias: Family Room Nightlight On
  trigger:
  - event: sunset
    platform: sun
  action:
  - data:
      brightness_pct: 66
      entity_id: light.hue_family_room_nightlight
    service: light.turn_on
  - data:
      message: Family room nightlight light is ON
    service: notify.kyles_phone
  - data:
      message: Family room nightlight light is On
    service: notify.kyles_tv
- id: '1541758470475'
  alias: Family Room Nightlight Off
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - data:
      entity_id: light.hue_family_room_nightlight
    service: light.turn_off
  - data:
      message: Family room nightlight light is Off
    service: notify.kyles_phone
  - data:
      message: Family room nightlight light is Off
    service: notify.kyles_tv
- id: '1543673341335'
  alias: Outside Lights On
  trigger:
  - event: sunset
    offset: +00:30:00
    platform: sun
  condition: []
  action:
  - data:
      brightness_pct: 66
      color_name: yellow
      entity_id: light.hue_garage_door_left
    service: light.turn_on
  - data:
      brightness_pct: 66
      color_name: yellow
      entity_id: light.hue_garage_door_right
    service: light.turn_on  - data:
  - data:
      brightness_pct: 20
      color_name: blue
      entity_id: light.hue_front_porch
    service: light.turn_on
- id: '1543673628316'
  alias: Outside Lights Off
  trigger:
  - event: sunrise
    offset: -00:30:00
    platform: sun
  condition: []
  action:
  - data:
      entity_id: group.outside_lights
    service: light.turn_off
- id: '1544367955335'
  alias: Target Reminder
  trigger:
  - entity_id: device_tracker.kyle_phone
    event: enter
    platform: zone
    zone: zone.target_southpoint
  condition: []
  action:
  - data:
      message: Check Target List
    service: notify.kyles_phone
- id: '1544368039706'
  alias: Harris Teeter Reminder
  trigger:
  - entity_id: device_tracker.kyle_phone
    event: enter
    platform: zone
    zone: zone.harris_teeter
  condition: []
  action:
  - data:
      message: Check Grocery List
    service: notify.kyles_phone
- id: '1544374019580'
  alias: Turn OFF Tv when I leave
  trigger:
  - entity_id: device_tracker.kyle_kylephone
    event: leave
    platform: zone
    zone: zone.home
  condition: []
  action:
  - data:
      entity_id: media_player.kyles_tv
    service: homeassistant.turn_off
- id: '1545128379623'
  alias: Kyles Phone Battery Low
  trigger:
  - below: '20'
    entity_id: sensor.kyle_phone_battery
    platform: numeric_state
  condition: []
  action:
  - data:
      message: Phone battery below 20%
    service: notify.kyles_phone
- id: '1545128460515'
  alias: Kyles phone fully charged
  trigger:
  - entity_id: sensor.kyle_phone_battery
    from: '99'
    platform: state
    to: '100'
  condition: []
  action:
  - data:
      message: Phone is fully charged
    service: notify.kyles_phone
