- id: '1541109387657'
  alias: Family Room Nightlight On
  trigger:
  - event: sunset
    platform: sun
  action:
  - data:
      brightness_pct: 66
      entity_id: light.hue_family_room_nightlight
    service: light.turn_on
  - data:
      message: Family room nightlight light is ON
    service: notify.kyles_phone
  - data:
      message: Family room nightlight light is On
    service: notify.kyles_tv
- id: '1541758470475'
  alias: Family Room Nightlight Off
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - data:
      entity_id: light.hue_family_room_nightlight
    service: light.turn_off
  - data:
      message: Family room nightlight light is Off
    service: notify.kyles_phone
  - data:
      message: Family room nightlight light is Off
    service: notify.kyles_tv
- id: '1543673341335'
  alias: Outside Garage Lights On
  trigger:
  - event: sunset
    offset: +00:30:00
    platform: sun
  condition: []
  action:
  - data:
      color_name: green
      entity_id: light.hue_garage_door_left
    service: light.turn_on
  - data:
      color_name: blue
      entity_id: light.hue_garage_door_right
    service: light.turn_on
- id: '1543673628316'
  alias: Outside Garage Lights Off
  trigger:
  - event: sunrise
    offset: -00:30:00
    platform: sun
  condition: []
  action:
  - data:
      entity_id: group.garage_door_lights
    service: light.turn_off
- id: '1544367955335'
  alias: Target Reminder
  trigger:
  - entity_id: device_tracker.kyle_phone
    event: enter
    platform: zone
    zone: zone.target_southpoint
  condition: []
  action:
  - data:
      message: Check Target List
    service: notify.kyles_phone
- id: '1544368039706'
  alias: Harris Teeter Reminder
  trigger:
  - entity_id: device_tracker.kyle_phone
    event: enter
    platform: zone
    zone: zone.harris_teeter
  condition: []
  action:
  - data:
      message: Check Grocery List
    service: notify.kyles_phone
- id: '1544374019580'
  alias: Turn OFF Tv when I leave
  trigger:
  - entity_id: device_tracker.kyle_kylephone
    event: leave
    platform: zone
    zone: zone.home
  condition: []
  action:
  - data:
      entity_id: media_player.kyles_tv
    service: homeassistant.turn_off
- id: Set HA theme for day or night
  alias: Set HA theme for day or night
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: sun.sun
    to: above_horizon
  - platform: state
    entity_id: sun.sun
    to: below_horizon
  action:
  - service_template: frontend.set_theme
    data_template:
      name: '{% if states.sun.sun.state == "below_horizon" %} Dark-Green {% else %}
        default {% endif %}'
- id: '1545128379623'
  alias: Kyles Phone Battery Low
  trigger:
  - below: '20'
    entity_id: sensor.kyle_phone_battery
    platform: numeric_state
  condition: []
  action:
  - data:
      message: Phone battery below 20%
    service: notify.kyles_phone
- id: '1545128460515'
  alias: Kyles phone fully charged
  trigger:
  - entity_id: sensor.kyle_phone_battery
    from: '99'
    platform: state
    to: '100'
  condition: []
  action:
  - data:
      message: Phone is fully charged
    service: notify.kyles_phone
