- id: 'Family Room Nightlight On'
  alias: Family Room Nightlight On
  initial_state: true
  trigger:
  - event: sunset
    platform: sun
  action:
  - service: light.turn_on
    data:
      brightness_pct: 66
      entity_id: light.hue_family_room_nightlight
  - service: notify.kyles_phone
    data:
      message: Family room nightlight light is ON
  - service: notify.kyles_tv
    data:
      message: Family room nightlight light is On
    
- id: 'Family Room Nightlight Off'
  alias: Family Room Nightlight Off
  initial_state: true
  trigger:
  - platform: sun
    event: sunrise
  condition: []
  action:
  - service: light.turn_off
    entity_id: light.hue_family_room_nightlight
  - service: notify.kyles_phone
    data:
      message: Family room nightlight light is Off
  - service: notify.kyles_tv
    data:
      message: Family room nightlight light is Off
   
- id: 'Outside Lights On'
  alias: Outside Lights On
  initial_state: true
  trigger:
  - event_data:
      offset: +00:30:00
    event_type: sun
    platform: event
  condition: []
  action:
  - data:
      brightness_pct: 80
      color_name: yellow
      entity_id: light.hue_garage_door_left
    service: light.turn_on
  - data:
      brightness_pct: 80
      color_name: yellow
      entity_id: light.hue_garage_door_right
    service: light.turn_on
  - data:
      brightness_pct: 20
      color_name: blue
      entity_id: light.hue_front_porch
    service: light.turn_on

- id: 'Outside Lights Off'
  initial_state: true
  alias: Outside Lights Off
  trigger:
  - event: sunrise
    offset: -00:30:00
    platform: sun
  condition: []
  action:
  - data:
      entity_id: light.hue_garage_door_left
    service: light.turn_off
  - data:
      entity_id: light.hue_garage_door_right
    service: light.turn_off
  - data:
      entity_id: light.hue_front_porch
    service: light.turn_off
   