homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include customize.yaml
  # Comment this
  packages: !include_dir_named packages


##############################################
#                                            #
#               INCLUDES                     #
#                                            #
##############################################
group: !include_dir_merge_named groups
automation: !include automations.yaml
script: !include scripts.yaml
panel_iframe: !include iframe.yaml
camera: !include devices/cameras.yaml
sensor: !include_dir_merge_list sensors/
notify: !include notify.yaml
#android_ip_webcam: !include devices/android_ip_webcam.yaml
history_graph: !include history-graphs.yaml
zone: !include zones.yaml

##############################################
#                                            #
#              INTEGRATIONS                  #
#                                            #
##############################################

# Show links to resources in lo and frontend
#introduction:

# Enables running python scripts
python_script:

#mqtt:
#  broker: !secret mqtt_broker_addr

system_health:

device_tracker:
  - platform: google_maps
    username: !secret ha_gmail_addr
    password: !secret ha_gmail_pass
    max_gps_accuracy: 200

# Enables the frontend
frontend:
  javascript_version: auto
  themes: !include_dir_merge_named themes

# Enables configuration UI
config:

# Use ui-lovelace.yaml
lovelace:
  mode: yaml
  
# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:
  include:
    domains:
      - light
#    entities:
#      - sensor.memory_free
#      - sensor.memory_use
#      - sensor.memory_use_percent
#      - sensor.disk_use_percent_
#      - sensor.disk_free_
#      - sensor.disk_use_
#      - sensor.swap_free
#      - sensor.swap_use
#      - sensor.swap_use_percent
#      - sensor.load_1m
#      - sensor.load_5m
#      - sensor.load_15m
#      - sensor.processor_use

# View all events in a logbook
logbook:
  include:
    domains:
      - light
      - device_tracker

# Set the log level in home-assistant.log
logger:
  default: info

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

# Cloud
#cloud:

weather:
  - platform: darksky
    api_key: !secret dark_sky_api_key

# Hue lights hub
hue:
  bridges:
    - host: !secret hue_hub_addr

# Telegram messaging
telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret kyles_phone_telegram_chat_id

#SSL/TLS
#http:
#  api_password: !secret hass_pass
#  ssl_certificate: !secret dehydrate_ssl_cert_path
#  ssl_key: !secret dehydrate_ssl_key_path
#  base_url: !secret dyn_dns_addr

media_player:
  - platform: webostv
    host: !secret kyle_tv
    name: kyles tv
    filename: webostv.conf
#  - platform: roku
#    host: !secret kyle_roku
#    name: kyle_roku

shell_command:
  test_touch: 'chdir /tmp && touch test_touch_file'
  git_pull: 'chdir /home/.homeassistant && /usr/local/bin/git pull origin master > git.log'
  who_am_i: whoami > /home/out.log

rachio:
  api_key: !secret rachio_api_key
  
#sensor:
#  - platform: transmission
transmission:
  host: 192.168.1.102
  name: transmission series
  monitored_conditions:
    - current_status
    - download_speed
    - upload_speed
    - active_torrents
    - paused_torrents
    - total_torrents
    
#  - platform: transmission
#  - host: 192.168.1.107
#    name: transmission other
#    monitored_conditions:
#      - 'current_status'
#      - 'download_speed'
#      - 'upload_speed'
#      - 'active_torrents'
#      - 'paused_torrents'
#      - 'total_torrents'

#  - platform: sonarr_upcoming_media
#    api_key: !secret sonarr_api_key
#    host: !secret sonarr_addr
#    port: 8989
#    days: 7
#    urlbase: /usr/local/share/sonarr/
#    ssl: false
#    max: 20
