- platform: smtp
  name: kyles_phone
  server: smtp.gmail.com
  port: 587
  timeout: 15
  sender: !secret ha_gmail_addr
  encryption: starttls
  username: !secret ha_gmail_addr
  password: !secret ha_gmail_pass
  recipient: !secret kyle_phone_txt_addr
  sender_name: Home Assistant
   
- name: kyles_tv
  host: !secret kyle_tv
  platform: webostv
  filename: webostv.conf

- platform: smtp
  name: gmail
  server: smtp.gmail.com
  port: 587
  timeout: 15
  sender: !secret ha_gmail_addr
  encryption: starttls
  username: !secret ha_gmail_addr
  password: !secret ha_gmail_pass
  recipient: !secret kyle_gmail_addr
  sender_name: Home Assistant