views:
  - title: main
    icon: mdi:home-outline
    panel: true
    cards: #!include cards/home.yaml
      - type: vertical-stack
        cards:
        - type: horizontal-stack
          cards:
          - type: vertical-stack
            cards:
              - type: markdown
                content: >
                  ## Current Conditions
              - type: entities
                entities:
                  - sensor.pws_alerts
              - type: entities
                entities:
                  - sensor.pws_temp_f
              - type: entities
                entities:
                  - sensor.pws_relative_humidity
              - type: entities
                entities:
                  - sensor.pws_dewpoint_f
              - type: entities
                entities:
                  - sensor.pws_feelslike_f
              - type: entities
                entities:
                  - sensor.pws_heat_index_f
              - type: entities
                entities:
                  - sensor.pws_wind_mph
              - type: entities
                entities:
                  - sensor.pws_wind_dir
              - type: entities
                entities:
                  - sensor.pws_wind_string
              - type: entities
                entities:
                  - sensor.pws_visibility_mi
              - type: entities
                entities:
                  - sensor.pws_solarradiation
              - type: entity-filter
                entities:
                  - sensor.pws_UV
                state_filter:
                  - 'unavailable'
                  
          - type: vertical-stack
            cards:
              - type: markdown
                content: >
                  ## Hourly Forecast
              - type: entities
                entities:
                  - sensor.weather_1h_summary
              - type: entities
                entities:
                  - sensor.weather_2h_summary
              - type: entities
                entities:
                  - sensor.weather_3h_summary
              - type: entities
                entities:
                  - sensor.weather_4h_summary
              - type: entities
                entities:
                  - sensor.weather_5h_summary
              - type: entities
                entities:
                  - sensor.weather_6h_summary
              - type: entities
                entities:
                  - sensor.weather_9h_summary
              - type: entities
                entities:
                  - sensor.weather_12h_summary
              - type: entities
                entities:
                  - sensor.weather_18h_summary
              - type: entities
                entities:
                  - sensor.weather_24h_summary

          - type: vertical-stack
            cards:
              - type: markdown
                content: >
                  ## Daily Forecast
              - type: entities
                entities:
                  - sensor.pws_weather_1d
              - type: entities
                entities:
                  - sensor.pws_weather_1n
              - type: entities
                entities:
                  - sensor.pws_weather_2d
              - type: entities
                entities:
                  - sensor.pws_weather_2n
              - type: entities
                entities:
                  - sensor.pws_weather_3d
              - type: entities
                entities:
                  - sensor.pws_weather_3n
              - type: entities
                entities:
                  - sensor.pws_weather_4d
              - type: entities
                entities:
                  - sensor.pws_weather_4n

        - type: horizontal-stack
          cards:
          - type: vertical-stack
            cards:
              - type: markdown
                content: >
                  ## Radar
              - type: picture-glance
                # Don't show a title, but a value is necessary 
                # to center the camera_image icon
                title: " "
                entities:
                  - camera.raleigh_radar
                camera_image: camera.raleigh_satellite
                

          - type: vertical-stack
            cards:
              - title: Porch Lights
                type: glance
                entities:
                  - entity: light.hue_front_porch
                    icon: mdi:home
                  - entity: light.hue_garage_door_left
                    icon: mdi:garage
                  - entity: light.hue_garage_door_right  
                    icon: mdi:garage
          
              - title: Web Links
                type: entities
                entities:
                  - type: weblink
                    url: https://www.mynexia.com/login
                    icon: mdi:thermostat
                    name: mynexia

  - title: weather
    icon: mdi:cloud-outline
    cards:
      - title: Sun
        type: entities
        entities:
          - sun.sun
          - sensor.sunrise_time
          - sensor.sunset_time
          - sensor.sunrise_dawn
          - sensor.sunset_dusk
 
      - title: Summary
        type: entities
        entities:
          - sensor.pws_weather
          - sensor.pws_temp_f
          - sensor.pws_station_id
          - sensor.pws_elevation
          - sensor.pws_location
          - sensor.pws_observation_time
          - sensor.pws_solarradiation
          - sensor.pws_visibility_mi
          - sensor.pws_alerts

      - title: Comfort
        type: entities
        entities:
          - sensor.pws_feelslike_f
          - sensor.pws_feelslike_string
          - sensor.pws_heat_index_f
          - sensor.pws_heat_index_string
          - sensor.pws_dewpoint_f
          - sensor.pws_dewpoint_string
          - sensor.pws_relative_humidity
          - sensor.pws_UV

      - title: Wind
        type: entities
        entities:
          - sensor.pws_wind_gust_1d_mph
          - sensor.pws_wind_1d_mph
          - sensor.pws_pressure_in
          - sensor.pws_pressure_mb
          - sensor.pws_pressure_trend
          - sensor.pws_wind_mph
          - sensor.pws_wind_dir
          - sensor.pws_wind_degrees
          - sensor.pws_wind_string
  
      - title: Precipitation
        type: entities
        entities:
          - sensor.pws_precip_1d_in
          - sensor.pws_precip_1d
          - sensor.pws_precip_1hr_in
          - sensor.pws_precip_today_in
          - sensor.pws_precip_today_string
          
  - title: lights
    icon: mdi:lightbulb-outline
    cards:
      - title: Family Room Lights
        type: entities
        entities:
          - light.hue_family_room_nightlight
      
      - title: Porch Lights
        type: entities
        entities:
          - light.hue_front_porch

      - title: Garage Door Lights
        type: entities
        entities:
          - light.hue_garage_door_left
          - light.hue_garage_door_right  

      - title: All Outside Lights
        type: entities
        entities:
          - group.porch_lights
          - group.garage_door_lights
      
  - title: media
    icon: mdi:television
    cards:
      - title: Kyles TV
        type: entities
        entities:
          - media_player.kyles_tv
          - media_player.kyle_roku
  - title: system
    icon: mdi:desktop-tower
    cards:
      - title: Memory
        type: entities
        entities:
          - sensor.memory_free
          - sensor.memory_use
          - sensor.memory_use_percent

      - title: Disk
        type: entities
        entities:
          - sensor.disk_use_percent_
          - sensor.disk_free_
          - sensor.disk_use_
          - sensor.swap_free
          - sensor.swap_use
          - sensor.swap_use_percent
      
      - title: Network
        type: entities
        entities:
          - sensor.ipv4_address
          - sensor.network_in
          - sensor.network_out
          - sensor.packets_in
          - sensor.packets_out

      - title: System
        type: entities
        entities:
          - sensor.last_boot
          - sensor.since_last_boot
          - sensor.load_1m
          - sensor.load_5m
          - sensor.load_15m
          - sensor.process

      - title: CPU
        type: entities
        entities:
          - sensor.processor_use

      - title: CPU 0 Temp
        type: history-graph
        entities:
          - sensor.cpu0_temp
        refresh_interval: 60
          
      - title: CPU 1 Temp
        type: history-graph
        entities:
          - sensor.cpu1_temp
        refresh_interval: 60
          
      - title: CPU 2 Temp
        type: history-graph
        entities:
          - sensor.cpu2_temp
        refresh_interval: 60
          
      - title: CPU 3 Temp
        type: history-graph
        entities:
          - sensor.cpu3_temp
        refresh_interval: 60
          
      - title: CPU 4 Temp
        type: history-graph
        entities:
          - sensor.cpu4_temp
        refresh_interval: 60
          
      - title: CPU 5 Temp
        type: history-graph
        entities:
          - sensor.cpu5_temp
        refresh_interval: 60
          
      - title: CPU 6 Temp
        type: history-graph
        entities:
          - sensor.cpu6_temp
        refresh_interval: 60
          
      - title: CPU 7 Temp
        type: history-graph
        entities:
          - sensor.cpu7_temp
        refresh_interval: 60
          
  - title: web cams
    icon: mdi:camcorder
#    cards:
#      - title: Web Cams
#        type: picture-glance
#        entities:
#          - camera.kitchen_camera
#        camera_image: camera.kitchen_camera
