###############################
#                             #
#         Resources           #
#                             #
###############################
resources:
  - url: /local/custom-lovelace/upcoming-media-card/upcoming-media-card.js?v=0.0.1
    type: js

###############################
#                             #
#           Views             #
#                             #
###############################
views:
###############################
#                             #
#         Home Tab            #
#                             #
###############################
  - title: main
    icon: mdi:home-outline
    panel: true
    cards: #!include cards/home.yaml
      - type: vertical-stack
        cards:
        - type: vertical-stack
          cards:
          - type: markdown
            content: >
              ## Kyle's Phone Information
          - type: horizontal-stack
            cards:
            - type: glance
              entities:
                - device_tracker.kyle_phone
            - type: glance
              entities:
                - sensor.kyle_phone_battery
        - type: horizontal-stack
          cards:
          - type: vertical-stack
            cards:
              - type: markdown
                content: >
                  ## Current Conditions
              - type: horizontal-stack
                cards:
                - type: glance
                  entities:
                    - sensor.pws_alerts
                - type: glance
                  entities:
                    - sensor.pws_temp_f
                - type: glance
                  entities:
                    - sensor.pws_relative_humidity
              - type: horizontal-stack
                cards:
                - type: glance
                  entities:
                    - sensor.pws_dewpoint_f
                - type: glance
                  entities:
                    - sensor.pws_feelslike_f
                - type: glance
                  entities:
                    - sensor.pws_heat_index_f
              - type: horizontal-stack
                cards:
                - type: glance
                  entities:
                    - sensor.pws_wind_mph
                - type: glance
                  entities:
                    - sensor.pws_wind_dir
                - type: glance
                  entities:
                    - sensor.pws_wind_string
              - type: horizontal-stack
                cards:
                - type: glance
                  entities:
                    - sensor.pws_visibility_mi
                - type: glance
                  entities:
                    - sensor.pws_solarradiation
                - type: conditional
                  conditions:
                    - entity: sensor.pws_UV
                      state_not: 'unavailable'
                  card:
                    type: glance
                    entities:
                      - sensor.pws_UV

          - type: vertical-stack
            cards:
              - type: markdown
                content: >
                  ## Hourly Forecast
              - type: entities
                entities:
                  - sensor.weather_1h_summary
              - type: entities
                entities:
                  - sensor.weather_2h_summary
              - type: entities
                entities:
                  - sensor.weather_3h_summary
              - type: entities
                entities:
                  - sensor.weather_4h_summary
              - type: entities
                entities:
                  - sensor.weather_5h_summary
              - type: entities
                entities:
                  - sensor.weather_6h_summary
              - type: entities
                entities:
                  - sensor.weather_9h_summary
              - type: entities
                entities:
                  - sensor.weather_12h_summary
              - type: entities
                entities:
                  - sensor.weather_18h_summary
              - type: entities
                entities:
                  - sensor.weather_24h_summary

          - type: vertical-stack
            cards:
              - type: markdown
                content: >
                  ## Daily Forecast
              - type: entities
                entities:
                  - sensor.pws_weather_1d
              - type: entities
                entities:
                  - sensor.pws_weather_1n
              - type: entities
                entities:
                  - sensor.pws_weather_2d
              - type: entities
                entities:
                  - sensor.pws_weather_2n
              - type: entities
                entities:
                  - sensor.pws_weather_3d
              - type: entities
                entities:
                  - sensor.pws_weather_3n
              - type: entities
                entities:
                  - sensor.pws_weather_4d
              - type: entities
                entities:
                  - sensor.pws_weather_4n

        - type: horizontal-stack
          cards:
          - type: vertical-stack
            cards:
              - type: markdown
                content: >
                  ## Radar
              - type: picture-glance
                # Don't show a title, but a value is necessary
                # to center the camera_image icon
                title: " "
                entities:
                  - camera.raleigh_radar
                camera_image: camera.raleigh_satellite


          - type: vertical-stack
            cards:
              - title: Porch Lights
                type: glance
                entities:
                  - entity: light.hue_front_porch
                    icon: mdi:home
                  - entity: light.hue_garage_door_left
                    icon: mdi:garage
                  - entity: light.hue_garage_door_right
                    icon: mdi:garage

              - title: Web Links
                type: entities
                entities:
                  - type: weblink
                    url: https://www.mynexia.com/login
                    icon: mdi:thermostat
                    name: mynexia

###############################
#                             #
#        Weather Tab          #
#                             #
###############################
  - title: weather
    icon: mdi:cloud-outline
    panel: true
    cards:
      # Parent card
      - type: vertical-stack
        cards:
        # Row - Sun / Summary / Comfort cards
        - type: horizontal-stack
          cards:
          # Column Sun / Comfort
          - type: vertical-stack
            cards:
            # Row Sun Sensor
            - type: markdown
              content: >
                ## Sun
            - type: glance
              entities:
                - sun.sun
                - sensor.sunrise_time
                - sensor.sunset_time
                - sensor.sunrise_dawn
                - sensor.sunset_dusk
            # Row - Weather Comfort
            - type: markdown
              content: >
                ## Comfort
            # Row - Weather Confort Values
            - type: horizontal-stack
              cards:
              - type: glance
                entities:
                  - sensor.pws_feelslike_f
              - type: glance
                entities:
                  - sensor.pws_heat_index_f
              - type: glance
                entities:
                  - sensor.pws_dewpoint_f
              - type: glance
                entities:
                  - sensor.pws_relative_humidity
            # Row - Weather Comfort Strings
            - type: horizontal-stack
              cards:
              - type: glance
                entities:
                  - sensor.pws_feelslike_string
              - type: glance
                entities:
                  - sensor.pws_heat_index_string
              - type: glance
                entities:
                  - sensor.pws_dewpoint_string
              - type: conditional
                conditions:
                  - entity: sensor.pws_UV
                    state_not: 'unavailable'
                card:
                  type: glance
                  entities:
                    - sensor.pws_UV
          # Column - Weather Summary
          - type: vertical-stack
            cards:
            # Row Station ID / Elevation / Location
            - type: markdown
              content: >
                ## Station
            - type: horizontal-stack
              cards:
              - type: glance
                entities:
                  - sensor.pws_station_id
              - type: glance
                entities:
                  - sensor.pws_elevation
              - type: glance
                entities:
                  - sensor.pws_location
            - type: markdown
              content: >
                ## Summary
            # Row - Weather / Temp / Visibility
            - type: horizontal-stack
              cards:
              - type: glance
                entities:
                  - sensor.pws_weather
              - type: glance
                entities:
                  - sensor.pws_temp_f
              - type: glance
                entities:
                  - sensor.pws_visibility_mi
            # Row Alerts / Solar Radiation / Observation Time
            - type: horizontal-stack
              cards:
              - type: glance
                entities:
                  - sensor.pws_alerts
              - type: glance
                entities:
                  - sensor.pws_solarradiation
              - type: glance
                entities:
                  - sensor.pws_observation_time_short_date
        # Row - Wind / Precipitation cards
        - type: horizontal-stack
          cards:
          # Column - Wind
          - type: vertical-stack
            cards:
            - type: markdown
              content: >
                ## Wind
            - type: horizontal-stack
              cards:
              - type: glance
                entities:
                  - sensor.pws_wind_gust_1d_mph
              - type: glance
                entities:
                  - sensor.pws_wind_1d_mph
              - type: glance
                entities:
                  - sensor.pws_pressure_in
            - type: horizontal-stack
              cards:
              - type: glance
                entities:
                  - sensor.pws_pressure_mb
              - type: glance
                entities:
                  - sensor.pws_pressure_trend
              - type: glance
                entities:
                  - sensor.pws_wind_mph
            - type: horizontal-stack
              cards:
              - type: glance
                entities:
                  - sensor.pws_wind_dir
              - type: glance
                entities:
                  - sensor.pws_wind_degrees
              - type: glance
                entities:
                  - sensor.pws_wind_string

          # Column Precipitation
          - type: vertical-stack
            cards:
            - type: markdown
              content: >
                ## Precipitation
            - type: horizontal-stack
              cards:
              - type: glance
                entities:
                  - sensor.pws_precip_1d_in
              - type: glance
                entities:
                  - sensor.pws_precip_1d
            - type: horizontal-stack
              cards:
              - type: glance
                entities:
                  - sensor.pws_precip_1hr_in
              - type: glance
                entities:
                  - sensor.pws_precip_today_in
              - type: glance
                entities:
                  - sensor.pws_precip_today_string
      # End page

###############################
#                             #
#        Lights Tab           #
#                             #
###############################
  - title: lights
    icon: mdi:lightbulb-outline
    panel: true
    cards:
      # Parent card
      - type: vertical-stack
        cards:
        # Row - Clock Sensor
        - type: glance
          entities:
            - entity: sensor.time
        # Row - Interior Lights
        - type: horizontal-stack
          cards:
          - type: vertical-stack
            cards:
            - type: markdown
              content: >
                ## Interior Lights
            - type: glance
              entities:
                - light.hue_family_room_nightlight
        # Row - Outdor Lights
        - type: horizontal-stack
          cards:
          - type: vertical-stack
            cards:
            - type: markdown
              content: >
                ## Outdoor Lights
            - type: horizontal-stack
              cards:
                - type: glance
                  entities:
                    - entity: light.hue_front_porch
                      tap_action: toggle
                - type: glance
                  entities:
                    - entity: light.hue_garage_door_left
                      tap_action: toggle
                    - entity: light.hue_garage_door_right
                      tap_action: toggle
                - type: glance
                  entities:
                    - entity: group.porch_lights
                      tap_action: toggle
                    - entity: group.garage_door_lights
                      tap_action: toggle

###############################
#                             #
#        Media Tab            #
#                             #
###############################
  - title: media
    icon: mdi:television
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:upcoming-media-card
                entity: sensor.sonarr_upcoming_media
                title: Upcoming TV
                all_shadows: false
              - type: conditional
                conditions:
                  - entity: media_player.kyles_tv
                    state_not: 'unavailable'
                card:
                  type: glance
                  title: "Kyle's TV"
                  show_name: false
                  entities:
                    - media_player.kyles_tv
              - type: conditional
                conditions:
                  - entity: media_player.kylekyle_roku_roku
                    state_not: 'unavailable'
                card:
                  type: glance
                  show_name: false
                  entities:
                    - media_player.
              - title: Sonarr Queue
                type: glance
                show_name: false
                entities:
                  - sensor.sonarr_queue

###############################
#                             #
#        System Tab           #
#                             #
###############################
  - title: system
    icon: mdi:desktop-tower
    panel: true
    cards:
    # Parent card
    - type: vertical-stack
      cards:
      # Row - Memory / Disk / System
      - type: horizontal-stack
        cards:
        # Column Memory
        - type: vertical-stack
          cards:
          - type: markdown
            content: >
              ## Memory
          - type: vertical-stack
            cards:
            - type: glance
              entities:
                - sensor.memory_free
            - type: glance
              entities:
                - sensor.memory_use
            - type: glance
              entities:
                - sensor.memory_use_percent
        # Column Disk
        - type: vertical-stack
          cards:
          - type: markdown
            content: >
              ## Disk
          - type: horizontal-stack
            cards:
            - type: vertical-stack
              cards:
              - type: glance
                entities:
                  - sensor.disk_use_percent_
              - type: glance
                entities:
                  - sensor.disk_free_
              - type: glance
                entities:
                  - sensor.disk_use_
            - type: vertical-stack
              cards:
              - type: glance
                entities:
                  - sensor.swap_free
              - type: glance
                entities:
                  - sensor.swap_use
              - type: glance
                entities:
                  - sensor.swap_use_percent
        # Column System
        - type: vertical-stack
          cards:
          - type: markdown
            content: >
              ## System
          - type: horizontal-stack
            cards:
            - type: glance
              entities:
                - sensor.last_boot
            - type: glance
              entities:
                - sensor.since_last_boot
          - type: horizontal-stack
            cards:
            - type: glance
              entities:
                - sensor.load_1m
            - type: glance
              entities:
                - sensor.load_5m
            - type: glance
              entities:
                - sensor.load_15m
          - type: horizontal-stack
            cards:
            - type: glance
              entities:
                - sensor.processor_use
            - type: glance
              entities:
                - sensor.packets_in
            - type: glance
              entities:
                - sensor.packets_out
      # Row CPU Temps
      - type: vertical-stack
        cards:
        - type: history-graph
          entities:
            - sensor.cpu0_temp
          refresh_interval: 60
        - type: history-graph
          entities:
            - sensor.cpu1_temp
          refresh_interval: 60
        - type: history-graph
          entities:
            - sensor.cpu2_temp
          refresh_interval: 60
        - type: history-graph
          entities:
            - sensor.cpu3_temp
          refresh_interval: 60
        - type: history-graph
          entities:
            - sensor.cpu4_temp
          refresh_interval: 60
        - type: history-graph
          entities:
            - sensor.cpu5_temp
          refresh_interval: 60
        - type: history-graph
          entities:
            - sensor.cpu6_temp
          refresh_interval: 60
        - type: history-graph
          entities:
            - sensor.cpu7_temp
          refresh_interval: 60

###############################
#                             #
#       Web Cams Tab          #
#                             #
###############################
#  - title: web cams
#    icon: mdi:camcorder
#    cards:
#      - title: Web Cams
#        type: picture-glance
#        entities:
#          - camera.kitchen_camera
#        camera_image: camera.kitchen_camera
