#- platform: sonarr
#  api_key: !secret sonarr_api_key
#  host: !secret sonarr_addr
#  monitored_conditions:
#    - upcoming
#    - queue
#  days: 7

- platform: sonarr_upcoming_media
  api_key: !secret sonarr_api_key
  host: !secret sonarr_addr
  port: 8989
  days: 2
  baseurl: /usr/local/share/sonarr/
  ssl: false
  max: 10