- platform: sonarr
  api_key: !secret sonarr_api_key
  host: !secret sonarr_addr
  monitored_conditions:
    - queue

- platform: sonarr_upcoming_media
  api_key: !secret sonarr_api_key
  host: !secret sonarr_addr
  port: 8989
  days: 7
  baseurl: /usr/local/share/sonarr/
  ssl: false
  max: 20
  
- platform: transmission
  host: 192.168.1.102
  name: transmission series
  monitored_variables:
    - 'current_status'
    - 'download_speed'
    - 'upload_speed'
    - 'active_torrents'
    - 'paused_torrents'
    - 'total_torrents'

- platform: transmission
  host: 192.168.1.107
  name: transmission other
  monitored_variables:
    - 'current_status'
    - 'download_speed'
    - 'upload_speed'
    - 'active_torrents'
    - 'paused_torrents'
    - 'total_torrents'
      