- platform: systemmonitor
  resources:
  - type: disk_use_percent
    arg: "/"
  - type: disk_use
    arg: "/"
  - type: disk_free
    arg: "/"
  - type: memory_free
  - type: memory_use_percent
  - type: memory_use
  - type: swap_use_percent
  - type: swap_use
  - type: swap_free
  - type: load_1m
  - type: load_5m
  - type: load_15m
  - type: processor_use
  - type: process
  - type: last_boot
  - type: since_last_boot

- platform: command_line
  name: ipv4_address
  command: "/sbin/ifconfig | /usr/bin/grep -w 'inet' | /usr/bin/grep -v '127.0.0.1' | /usr/bin/awk '{ print $2}'"

- platform: command_line
  name: Packets in
  command: "/usr/bin/netstat -s | grep -a20 'tcp:' | grep 'packets received' | awk '{ print $1 }'"
  
- platform: command_line
  name: Packets out
  command: "/usr/bin/netstat -s | grep -a20 'tcp:' | grep 'packets sent' | awk '{ print $1 }'"
  
#- platform: command_line
#  name: Network in
#  command: "atop -r /var/log/atop/atop_20181204 -P NET"
  
#- platform: command_line
#  name: Network out
#  command: "/usr/bin/netstat -s | grep -a20 tcp: | grep 'packets sent' | awk '{ print $1 }'"
  
- platform: command_line
  name: cpu0 Temp
  command: "/sbin/sysctl dev.cpu | grep dev.cpu.0.temperature | /usr/bin/awk -F ':' '{ print $2 }'"
  unit_of_measurement: "°C"

- platform: command_line
  name: cpu1 Temp
  command: "/sbin/sysctl dev.cpu | grep dev.cpu.1.temperature | /usr/bin/awk -F ':' '{ print $2 }'"
  unit_of_measurement: "°C"

- platform: command_line
  name: cpu2 Temp
  command: "/sbin/sysctl dev.cpu | grep dev.cpu.2.temperature | /usr/bin/awk -F ':' '{ print $2 }'"
  unit_of_measurement: "°C"

- platform: command_line
  name: cpu3 Temp
  command: "/sbin/sysctl dev.cpu | grep dev.cpu.3.temperature | /usr/bin/awk -F ':' '{ print $2 }'"
  unit_of_measurement: "°C"

- platform: command_line
  name: cpu4 Temp
  command: "/sbin/sysctl dev.cpu | grep dev.cpu.4.temperature | /usr/bin/awk -F ':' '{ print $2 }'"
  unit_of_measurement: "°C"

- platform: command_line
  name: cpu5 Temp
  command: "/sbin/sysctl dev.cpu | grep dev.cpu.5.temperature | /usr/bin/awk -F ':' '{ print $2 }'"
  unit_of_measurement: "°C"

- platform: command_line
  name: cpu6 Temp
  command: "/sbin/sysctl dev.cpu | grep dev.cpu.6.temperature | /usr/bin/awk -F ':' '{ print $2 }'"
  unit_of_measurement: "°C"

- platform: command_line
  name: cpu7 Temp
  command: "/sbin/sysctl dev.cpu | grep dev.cpu.7.temperature | /usr/bin/awk -F ':' '{ print $2 }'"
  unit_of_measurement: "°C"


  
  
  
  
