- platform: darksky
  api_key: !secret dark_sky_api_key 
  monitored_conditions:
    - summary
    - icon
    - nearest_storm_distance
    - cloud_cover
    
-  platform: wunderground
   api_key: !secret wu_pws_api_key
   pws_id: !secret wu_pws_id
   monitored_conditions:
      - weather
      - temp_f
      - station_id
      - elevation
      - location
      - observation_time
      - feelslike_f
      - feelslike_string
      - heat_index_f
      - heat_index_string
      - dewpoint_f
      - dewpoint_string
      - wind_mph
      - UV
      - pressure_in
      - pressure_mb
      - pressure_trend
      - wind_dir
      - wind_degrees
      - wind_string
      - relative_humidity
      - visibility_mi
      - precip_1hr_in
      - precip_today_in
      - precip_today_string
      - solarradiation
      - alerts
      - weather_1d
      - weather_1n
      - weather_2d
      - weather_2n
      - weather_3d
      - weather_3n
      - weather_4d
      - weather_4n
      - weather_1h
      - weather_6h
