- platform: darksky
  api_key: !secret dark_sky_api_key 
#  units: en
  scan_interval: 
    minutes: 3
  forecast:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
  hourly_forecast:
#    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 9
    - 12
    - 18
  monitored_conditions:
    - summary
    - icon
    - precip_type
    - precip_intensity
    - precip_probability
    - precip_accumulation
    - temperature
    - apparent_temperature
    - dew_point
    - wind_speed
#    - wind_gust
    - wind_bearing
    - cloud_cover
    - humidity
    - pressure
    - visibility
    - ozone
    - minutely_summary
    - hourly_summary
    - daily_summary
    - temperature_high
    - temperature_low
    - apparent_temperature_high
    - apparent_temperature_low
    - precip_intensity_max
    - uv_index
    - moon_phase
#    - sunrise_time
#    - sunset_time
    - nearest_storm_distance
    - nearest_storm_bearing

- platform: template
  sensors:
    weather_1h_summary:
      value_template: '{{ states.sensor.dark_sky_summary_1h.state }} with a {{ states.sensor.dark_sky_precip_probability_1h.state }}% chance of precipitation and {{ states.sensor.dark_sky_temperature_1h.state_with_unit }}.'
      friendly_name_template: '{% set timestamp = as_timestamp(states.weather.dark_sky.attributes.forecast[0].datetime) | timestamp_custom("%I:%M %p") %}{{ timestamp.lstrip("0") }}'
- platform: template
  sensors:
    weather_2h_summary:
      value_template: '{{ states.sensor.dark_sky_summary_2h.state }} with a {{ states.sensor.dark_sky_precip_probability_2h.state }}% chance of precipitation and {{ states.sensor.dark_sky_temperature_2h.state_with_unit }}.'
      friendly_name_template: '{% set timestamp = as_timestamp(states.weather.dark_sky.attributes.forecast[1].datetime) | timestamp_custom("%I:%M %p") %}{{ timestamp.lstrip("0") }}'

- platform: template
  sensors:
    weather_3h_summary:
      value_template: '{{ states.sensor.dark_sky_summary_3h.state }} with a {{ states.sensor.dark_sky_precip_probability_3h.state }}% chance of precipitation and {{ states.sensor.dark_sky_temperature_3h.state_with_unit }}.'
      friendly_name_template: '{% set timestamp = as_timestamp(states.weather.dark_sky.attributes.forecast[2].datetime) | timestamp_custom("%I:%M %p") %}{{ timestamp.lstrip("0") }}'
      
- platform: template
  sensors:
    weather_4h_summary:
      value_template: '{{ states.sensor.dark_sky_summary_4h.state }} with a {{ states.sensor.dark_sky_precip_probability_4h.state }}% chance of precipitation and {{ states.sensor.dark_sky_temperature_4h.state_with_unit }}.'
      friendly_name_template: '{% set timestamp = as_timestamp(states.weather.dark_sky.attributes.forecast[3].datetime) | timestamp_custom("%I:%M %p") %}{{ timestamp.lstrip("0") }}'

- platform: template
  sensors:
    weather_5h_summary:
      value_template: '{{ states.sensor.dark_sky_summary_5h.state }} with a {{ states.sensor.dark_sky_precip_probability_5h.state }}% chance of precipitation and {{ states.sensor.dark_sky_temperature_5h.state_with_unit }}.'
      friendly_name_template: '{% set timestamp = as_timestamp(states.weather.dark_sky.attributes.forecast[4].datetime) | timestamp_custom("%I:%M %p") %}{{ timestamp.lstrip("0") }}'

- platform: template
  sensors:
    weather_6h_summary:
      value_template: '{{ states.sensor.dark_sky_summary_6h.state }} with a {{ states.sensor.dark_sky_precip_probability_6h.state }}% chance of precipitation and {{ states.sensor.dark_sky_temperature_6h.state_with_unit }}.'
      friendly_name_template: '{% set timestamp = as_timestamp(states.weather.dark_sky.attributes.forecast[5].datetime) | timestamp_custom("%I:%M %p") %}{{ timestamp.lstrip("0") }}'

- platform: template
  sensors:
    weather_9h_summary:
      value_template: '{{ states.sensor.dark_sky_summary_9h.state }} with a {{ states.sensor.dark_sky_precip_probability_9h.state }}% chance of precipitation and {{ states.sensor.dark_sky_temperature_9h.state_with_unit }}.'
      friendly_name_template: '{% set timestamp = as_timestamp(states.weather.dark_sky.attributes.forecast[8].datetime) | timestamp_custom("%I:%M %p") %}{{ timestamp.lstrip("0") }}'

- platform: template
  sensors:
    weather_12h_summary:
      value_template: '{{ states.sensor.dark_sky_summary_12h.state }} with a {{ states.sensor.dark_sky_precip_probability_12h.state }}% chance of precipitation and {{ states.sensor.dark_sky_temperature_12h.state_with_unit }}.'
      friendly_name_template: '{% set timestamp = as_timestamp(states.weather.dark_sky.attributes.forecast[11].datetime) | timestamp_custom("%I:%M %p") %}{{ timestamp.lstrip("0") }}'

- platform: template
  sensors:
    weather_18h_summary:
      value_template: '{{ states.sensor.dark_sky_summary_18h.state }} with a {{ states.sensor.dark_sky_precip_probability_18h.state }}% chance of precipitation and {{ states.sensor.dark_sky_temperature_18h.state_with_unit }}.'
      friendly_name_template: '{% set timestamp = as_timestamp(states.weather.dark_sky.attributes.forecast[17].datetime) | timestamp_custom("%I:%M %p") %}{{ timestamp.lstrip("0") }}'

