- platform: darksky
  api_key: !secret dark_sky_api_key 
#  units: en
  scan_interval: 
    minutes: 3
  forecast:
    - 1
    - 2
    - 3
  hourly_forecast:
#    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 10
    - 12
    - 18
  monitored_conditions:
    - summary
    - icon
    - precip_type
    - precip_intensity
    - precip_probability
    - precip_accumulation
    - temperature
    - apparent_temperature
    - dew_point
    - wind_speed
#    - wind_gust
    - wind_bearing
    - cloud_cover
    - humidity
    - pressure
    - visibility
    - ozone
    - minutely_summary
    - hourly_summary
    - daily_summary
    - temperature_high
    - temperature_low
    - apparent_temperature_high
    - apparent_temperature_low
    - precip_intensity_max
    - uv_index
    - moon_phase
#    - sunrise_time
#    - sunset_time
    - nearest_storm_distance
    - nearest_storm_bearing

- platform: template
  sensors:
    weather_1h_summary:
      value_template: '{{ states.weather.dark_sky.attributes.forecast[0].condition[0]|upper }}{{ states.weather.dark_sky.attributes.forecast[0].condition[1:] }} with a {% if states.weather.dark_sky.attributes.forecast[0].precipitation|lower == "none" %}0{% else %}{{ states.weather.dark_sky.attributes.forecast[0].precipitation }}{% endif %}% chance of precipitation and {{ states.weather.dark_sky.attributes.forecast[0].temperature }} degrees.'
      friendly_name_template: '{% set timestamp = as_timestamp(states.weather.dark_sky.attributes.forecast[0].datetime) | timestamp_custom("%I:%M %p") %}{{ timestamp.lstrip("0") }}'

- platform: template
  sensors:
    weather_2h_summary:
      value_template: '{{ states.weather.dark_sky.attributes.forecast[1].condition[0]|upper }}{{ states.weather.dark_sky.attributes.forecast[1].condition[1:] }} with a {% if states.weather.dark_sky.attributes.forecast[1].precipitation|lower == "none" %}0{% else %}{{ states.weather.dark_sky.attributes.forecast[1].precipitation }}{% endif %}% chance of precipitation and {{ states.weather.dark_sky.attributes.forecast[1].temperature }} degrees.'
      friendly_name_template: '{% set timestamp = as_timestamp(states.weather.dark_sky.attributes.forecast[1].datetime) | timestamp_custom("%I:%M %p") %}{{ timestamp.lstrip("0") }}'

- platform: template
  sensors:
    weather_3h_summary:
      value_template: '{{ states.weather.dark_sky.attributes.forecast[2].condition[0]|upper }}{{ states.weather.dark_sky.attributes.forecast[2].condition[1:] }} with a {% if states.weather.dark_sky.attributes.forecast[2].precipitation|lower == "none" %}0{% else %}{{ states.weather.dark_sky.attributes.forecast[2].precipitation }}{% endif %}% chance of precipitation and {{ states.weather.dark_sky.attributes.forecast[2].temperature }} degrees.'
      friendly_name_template: '{% set timestamp = as_timestamp(states.weather.dark_sky.attributes.forecast[2].datetime) | timestamp_custom("%I:%M %p") %}{{ timestamp.lstrip("0") }}'
      
- platform: template
  sensors:
    weather_4h_summary:
      value_template: '{{ states.weather.dark_sky.attributes.forecast[3].condition[0]|upper }}{{ states.weather.dark_sky.attributes.forecast[3].condition[1:] }} with a {% if states.weather.dark_sky.attributes.forecast[3].precipitation|lower == "none" %}0{% else %}{{ states.weather.dark_sky.attributes.forecast[3].precipitation }}{% endif %}% chance of precipitation and {{ states.weather.dark_sky.attributes.forecast[3].temperature }} degrees.'
      friendly_name_template: '{% set timestamp = as_timestamp(states.weather.dark_sky.attributes.forecast[3].datetime) | timestamp_custom("%I:%M %p") %}{{ timestamp.lstrip("0") }}'

- platform: template
  sensors:
    weather_5h_summary:
      value_template: '{{ states.weather.dark_sky.attributes.forecast[4].condition[0]|upper }}{{ states.weather.dark_sky.attributes.forecast[4].condition[1:] }} with a {% if states.weather.dark_sky.attributes.forecast[4].precipitation|lower == "none" %}0{% else %}{{ states.weather.dark_sky.attributes.forecast[4].precipitation }}{% endif %}% chance of precipitation and {{ states.weather.dark_sky.attributes.forecast[4].temperature }} degrees.'
      friendly_name_template: '{% set timestamp = as_timestamp(states.weather.dark_sky.attributes.forecast[4].datetime) | timestamp_custom("%I:%M %p") %}{{ timestamp.lstrip("0") }}'

- platform: template
  sensors:
    weather_6h_summary:
      value_template: '{{ states.weather.dark_sky.attributes.forecast[5].condition[0]|upper }}{{ states.weather.dark_sky.attributes.forecast[5].condition[1:] }} with a {% if states.weather.dark_sky.attributes.forecast[5].precipitation|lower == "none" %}0{% else %}{{ states.weather.dark_sky.attributes.forecast[5].precipitation }}{% endif %}% chance of precipitation and {{ states.weather.dark_sky.attributes.forecast[5].temperature }} degrees.'
      friendly_name_template: '{% set timestamp = as_timestamp(states.weather.dark_sky.attributes.forecast[5].datetime) | timestamp_custom("%I:%M %p") %}{{ timestamp.lstrip("0") }}'

- platform: template
  sensors:
    weather_9h_summary:
      value_template: '{{ states.weather.dark_sky.attributes.forecast[8].condition[0]|upper }}{{ states.weather.dark_sky.attributes.forecast[8].condition[1:] }} with a {% if states.weather.dark_sky.attributes.forecast[8].precipitation|lower == "none" %}0{% else %}{{ states.weather.dark_sky.attributes.forecast[8].precipitation }}{% endif %}% chance of precipitation and {{ states.weather.dark_sky.attributes.forecast[8].temperature }} degrees.'
      friendly_name_template: '{% set timestamp = as_timestamp(states.weather.dark_sky.attributes.forecast[8].datetime) | timestamp_custom("%I:%M %p") %}{{ timestamp.lstrip("0") }}'

- platform: template
  sensors:
    weather_12h_summary:
      value_template: '{{ states.weather.dark_sky.attributes.forecast[11].condition[0]|upper }}{{ states.weather.dark_sky.attributes.forecast[11].condition[1:] }} with a {% if states.weather.dark_sky.attributes.forecast[11].precipitation|lower == "none" %}0{% else %}{{ states.weather.dark_sky.attributes.forecast[11].precipitation }}{% endif %}% chance of precipitation and {{ states.weather.dark_sky.attributes.forecast[11].temperature }} degrees.'
      friendly_name_template: '{% set timestamp = as_timestamp(states.weather.dark_sky.attributes.forecast[11].datetime) | timestamp_custom("%I:%M %p") %}{{ timestamp.lstrip("0") }}'

- platform: template
  sensors:
    weather_18h_summary:
      value_template: '{{ states.weather.dark_sky.attributes.forecast[17].condition[0]|upper }}{{ states.weather.dark_sky.attributes.forecast[17].condition[1:] }} with a {% if states.weather.dark_sky.attributes.forecast[17].precipitation|lower == "none" %}0{% else %}{{ states.weather.dark_sky.attributes.forecast[17].precipitation }}{% endif %}% chance of precipitation and {{ states.weather.dark_sky.attributes.forecast[17].temperature }} degrees.'
      friendly_name_template: '{% set timestamp = as_timestamp(states.weather.dark_sky.attributes.forecast[17].datetime) | timestamp_custom("%I:%M %p") %}{{ timestamp.lstrip("0") }}'

